{% set name = "openff-nagl-models" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3bda84bce1b6cf94285d9ba4ad2eb51629fb89686304c1b22c476ccb523ed80f

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python 3.10
    - pip
    - versioningit
    - setuptools
  run:
    - python >=3.10
    - platformdirs
    - importlib_resources
  run_constrained:
    - openff-nagl >=0.4.0

test:
  imports:
    - openff.nagl_models
  requires:
    - pip

about:
  home: https://github.com/openforcefield/openff-nagl-models
  summary: 'NAGL models released by the Open Force Field Initiative'
  description: |
    This package contains NAGL models released by the Open Force Field Initiative.
    They are intended to be used by OpenFF NAGL.
  license: CC-BY-4.0
  license_family: CC
  license_file: LICENSE
  doc_url: https://github.com/openforcefield/openff-nagl-models
  dev_url: https://github.com/openforcefield/openff-nagl-models

extra:
  recipe-maintainers:
    - lilyminium
