{% set python_min = "3.10"}
{% set name = "openff-nagl-models" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 62a157513a668bf8200932f59b1a5608c08371b63a4c8293ba46b2587385144b

build:
  number: 2

outputs:
  - name: openff-nagl-models
    files:
      exclude:
        - openff/nagl_models/models/**/*.py
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - versioneer-518
        - setuptools
      run:
        - python >={{ python_min }}
        - importlib_resources
        - platformdirs
      run_constrained:
        - openff-nagl >=0.4.0
    test:
      imports:
        - openff.nagl_models
      requires:
        - pip

  - name: openff-nagl-models-all
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('openff-nagl-models-base', exact=True) }}


about:
  home: https://github.com/openforcefield/openff-nagl-models
  summary: 'NAGL models released by the Open Force Field Initiative'
  description: |
    This package contains NAGL models released by the Open Force Field Initiative.
    They are intended to be used by OpenFF NAGL.
  license: CC-BY-4.0
  license_family: CC
  license_file: LICENSE
  doc_url: https://github.com/openforcefield/openff-nagl-models
  dev_url: https://github.com/openforcefield/openff-nagl-models

extra:
  recipe-maintainers:
    - lilyminium
