{% set name = "openff-nagl-models" %}
{% set version = "2026.09.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-nagl-models/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 756260b97f83cc2aa45f475d6d9f3a344fd4e961debe5998cbf6e94cbdc19c0a

build:
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - platformdirs
    - packaging
  run_constrained:
    - openff-nagl >=0.5.2
    - openff-toolkit >=0.17

test:
  imports:
    - openff.nagl_models
  requires:
    - pip
    - python {{ python_min }} 
    - packaging
  files:
    - test.py
  commands:
    - python test.py

about:
  home: https://github.com/openforcefield/openff-nagl-models
  summary: 'NAGL models released by the Open Force Field Initiative'
  description: |
    This package contains NAGL models released by the Open Force Field Initiative.
    They are intended to be used by OpenFF NAGL.
  license: CC-BY-4.0
  license_family: CC
  license_file: LICENSE
  doc_url: https://github.com/openforcefield/openff-nagl-models
  dev_url: https://github.com/openforcefield/openff-nagl-models

extra:
  recipe-maintainers:
    - lilyminium
    - mattwthompson
    - j-wags
